/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ventana;

import com.metodos.metodos;
import javax.swing.JOptionPane;

/**
 *
 * @author jose1
 */
public class Principal extends javax.swing.JFrame {

        int signo = 0, x =0, y =0, res;
        metodos m; 
        int vida, puntos;
     public Principal() {
        initComponents();
        lblPuntos.setText("0");
        lblVidas.setText("3");
        m= new metodos();
         x = m.numeroRandom(1, 10);
        y = m.numeroRandom(1, 10);
        res = m.comprobarOperacion(x, y,signo);
        signo = m.signoRandom();
        lblNumeroUno.setText(Integer.toString(x));
             lblNumeroDos.setText(Integer.toString(y));
            switch(signo){
            case 1: lblSigno.setText("+");
            break;
            case 2: lblSigno.setText("-");
            break;
            case 3: lblSigno.setText("*");
            break;
            case 4: lblSigno.setText("/");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSigno = new javax.swing.JLabel();
        lblNumeroUno = new javax.swing.JLabel();
        lblNumeroDos = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        btnGo = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblVidas = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSigno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblSigno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblSigno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 20, 20));

        lblNumeroUno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblNumeroUno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblNumeroUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 90, 30));

        lblNumeroDos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblNumeroDos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblNumeroDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 80, 30));

        txtResultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtResultadoKeyPressed(evt);
            }
        });
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 70, -1));

        btnGo.setText("Go");
        btnGo.setFocusable(false);
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 60, 40));

        lbl.setText("Puntos");
        getContentPane().add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 50, 20));

        lblPuntos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(lblPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 80, 20));

        jLabel2.setText("Vidas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lblVidas.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(lblVidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, 30));

        btnReiniciar.setText("Reset");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        setSize(new java.awt.Dimension(499, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
       
        
        int resIngresado = Integer.parseInt(txtResultado.getText());
       
       
        txtResultado.setText("");
        txtResultado.setRequestFocusEnabled(true);
        res = m.comprobarOperacion(x, y,signo);
         System.out.println("res = "+res);
        System.out.println("resIngresado = "+resIngresado);
        if(res==resIngresado){
            puntos = m.Addpuntos();
            lblPuntos.setText(""+puntos);
            x = m.numeroRandom(1, 10);
            y = m.numeroRandom(1, 10);
            signo = m.signoRandom();
             switch(signo){
            case 1: lblSigno.setText("+");
            break;
            case 2: lblSigno.setText("-");
            break;
            case 3: lblSigno.setText("*");
            break;
            case 4: lblSigno.setText("/");
        }
             lblNumeroUno.setText(Integer.toString(x));
             lblNumeroDos.setText(Integer.toString(y));
        }else{
            
                 vida =  m.actualizarVidas();
                lblVidas.setText(""+vida);
                if(vida == 0){
                    JOptionPane.showMessageDialog(rootPane, "GAME OVER");
                }
            
           
        }
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        
        puntos=0;
        vida=3;
        txtResultado.setText("");
        lblPuntos.setText("0");
        lblVidas.setText("3");
        m= new metodos();
         x = m.numeroRandom(1, 10);
        y = m.numeroRandom(1, 10);
        res = m.comprobarOperacion(x, y,signo);
        signo = m.signoRandom();
        lblNumeroUno.setText(Integer.toString(x));
             lblNumeroDos.setText(Integer.toString(y));
            switch(signo){
            case 1: lblSigno.setText("+");
            break;
            case 2: lblSigno.setText("-");
            break;
            case 3: lblSigno.setText("*");
            break;
            case 4: lblSigno.setText("/");
            }
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void txtResultadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResultadoKeyPressed
        try {
           if(evt.getKeyCode()==10){
               int resIngresado = Integer.parseInt(txtResultado.getText());
       
       
        txtResultado.setText("");
        txtResultado.setRequestFocusEnabled(true);
        res = m.comprobarOperacion(x, y,signo);
         System.out.println("res = "+res);
        System.out.println("resIngresado = "+resIngresado);
        if(res==resIngresado){
            puntos = m.Addpuntos();
            lblPuntos.setText(""+puntos);
            x = m.numeroRandom(1, 10);
            y = m.numeroRandom(1, 10);
            signo = m.signoRandom();
             switch(signo){
            case 1: lblSigno.setText("+");
            break;
            case 2: lblSigno.setText("-");
            break;
            case 3: lblSigno.setText("*");
            break;
            case 4: lblSigno.setText("/");
        }
             lblNumeroUno.setText(Integer.toString(x));
             lblNumeroDos.setText(Integer.toString(y));
        }else{
            
                 vida =  m.actualizarVidas();
                lblVidas.setText(""+vida);
                if(vida == 0){
                    JOptionPane.showMessageDialog(rootPane, "GAME OVER");
                }
            
           
        }
           }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_txtResultadoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblNumeroDos;
    private javax.swing.JLabel lblNumeroUno;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblSigno;
    private javax.swing.JLabel lblVidas;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
